name: seleniumCloud
tags:
  app: seleniumCloud

network:
  vpc:
    natGatewaySubnetName: Public
    maxAzs: 3
    
  subnets:
    # Client UI subnet
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

maintainance:
  image_cleanup:
    retention_days: 60
    repo_arns: "selenium/client_webapp,selenium/api"